### ISSUE TITLE
How updated is this repository?

### ISSUE THREAD

**Issue by forrestblade** [ukabu/dev-on-chromeos#1]
Just curious, I just cloned and am installing. How has far has your PB strayed from this setup?

**Comment by ukabu** [comment]
I did not made any major change for a long time. Maybe some new vscode plugins (I have to check).
I mostly do `sudo apt update; sudo apt upgrade` every now and then.

**Comment by ukabu** [comment]
I've played a bit to make a emoji font work in vscode, but not found a solution yet.

**Comment by forrestblade** [comment]
This is definitely the best chromeOS setup I've found so far for my dev needs.

**Comment by forrestblade** [comment]
Thank you!
